# Copyright 2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Check and enable secure boot
- name: "Get VM boot info"
  include_tasks: ../../common/vm_get_boot_info.yml

- name: "Initialize the change status of secure boot"
  ansible.builtin.set_fact:
    secure_boot_changed: false

- name: "Enable secure boot"
  when: not vm_secureboot_enabled | bool
  block:
    - name: "Shut down guest OS"
      include_tasks: ../utils/win_shutdown_restart.yml
      vars:
        set_win_power_state: "shutdown"

    - name: "Enable VM secure boot"
      include_tasks: ../../common/vm_set_boot_options.yml
      vars:
        secure_boot_enabled_set: true

    - name: "Power on VM after secure boot enabled"
      include_tasks: ../../common/vm_set_power_state.yml
      vars:
        vm_power_state_set: "powered-on"

    - name: "Update the inventory"
      include_tasks: ../utils/win_update_inventory.yml

    - name: "Get secure boot status in guest OS"
      include_tasks: ../utils/win_execute_cmd.yml
      vars:
        win_powershell_cmd: "Confirm-SecureBootUEFI"

    - name: Check secure boot is enabled in guest OS
      ansible.builtin.assert:
        that:
          - not win_powershell_cmd_output.failed
          - win_powershell_cmd_output.stdout_lines[0] == 'True'
        msg: "Secure boot enabled status in guest OS: {{ win_powershell_cmd_output.stdout_lines[0] }}"

    - name: "Set the changed status of secure boot"
      ansible.builtin.set_fact:
        secure_boot_changed: true