# Copyright 2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Add registry to download and install the PCA2023-signed boot manager"
  include_tasks: ../utils/win_execute_cmd.yml
  vars:
    win_powershell_cmd: >-
      reg add HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Secureboot /v AvailableUpdates /t REG_DWORD /d 0x100 /f

- name: "Restart guest OS"
  include_tasks: restart_os_twice.yml

- name: "Set path for copied new boot manager and snapshot name"
  ansible.builtin.set_fact:
    new_bootmgfw_path: "c:\\bootmgfw_2023.efi"
    snapshot_name_for_pca2023: "PCA2023SignedBootmgfw"

- name: "Copy new boot manager bootmgfw.efi"
  include_tasks: ../utils/win_execute_cmd.yml
  vars:
    win_powershell_cmd: >-
      mountvol s: /s;
      copy S:\EFI\Microsoft\Boot\bootmgfw.efi {{ new_bootmgfw_path }}
      
- name: "Copy sigcheck tools to guest OS"
  ansible.builtin.copy:
    src: ./sigcheck
    dest: "C:\\"
  delegate_to: "{{ vm_guest_ip }}"

- name: "Get certification info of {{ new_bootmgfw_path }} by sigcheck"
  include_tasks: ../utils/win_execute_cmd.yml
  vars:
    win_powershell_cmd: >-
      C:\sigcheck\sigcheck.exe -accepteula -i {{ new_bootmgfw_path }}| find "Windows UEFI CA 2023"
    win_execute_cmd_ignore_error: true

- name: "Check if {{ new_bootmgfw_path }} is sighed with PCA2023"
  ansible.builtin.assert:
    that:
      - win_powershell_cmd_output.stdout_lines is defined
      - win_powershell_cmd_output.stdout_lines | length != 0
    fail_msg: "{{ new_bootmgfw_path }} is not sighed with PCA2023"
    success_msg: "{{ new_bootmgfw_path }} is sighed with PCA2023"

#- name: "Take snapshot after installing new boot manager"
#  include_tasks: ../../common/vm_take_snapshot.yml
#  vars:
#    snapshot_name: "{{ snapshot_name_for_pca2023 }}"
#    snapshot_description: "New bootmgfw.efi signed by PCA2023 is installed"
