# Copyright 2023-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This case is to enable windows updates, disable sleep, diable firewall. Then reset the base snapshot.
#
- name: windows_basic_config
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Test case block"
      block:
        - name: "Test setup"
          include_tasks: ../setup/test_setup.yml
          vars:
            create_current_test_folder: true

        - name: "Enable and start Microsoft Store Install Service"
          include_tasks: ../utils/win_execute_cmd.yml
          vars:
            win_powershell_cmd: >-
              Set-Service -Name wuauserv -StartupType Automatic; Start-Service wuauserv;
              Set-Service -Name InstallService -StartupType Automatic; Start-Service InstallService;

        - name: "Disable OS sleep"
          include_tasks: ../utils/win_execute_cmd.yml
          vars:
            win_powershell_cmd: >- 
              powercfg /change monitor-timeout-ac 0; powercfg /change disk-timeout-ac 0; 
              powercfg /change standby-timeout-ac 0; powercfg /change hibernate-timeout-ac 0;

        - name: "Disable firewall in Windows guest OS"
          include_tasks: ../utils/win_execute_cmd.yml
          vars:
            win_powershell_cmd: "netsh advfirewall set allprofiles state off"

        - name: "Reset the base snapshot and remove the old one"
          include_tasks: ../../common/reset_base_snapshot.yml
          vars:
            remove_old_base_snapshot: true
      rescue:
        - name: "Test case failure"
          include_tasks: ../../common/test_rescue.yml
          vars:
            exit_testing_when_fail: true
