# Copyright 2023-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This case is to test Microsoft's Windows updates.
#   Install Windows .msu update package.
#
- name: windows_test
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Test case block"
      block:
        - name: "Test setup"
          include_tasks: ../setup/test_setup.yml
          vars:
            create_current_test_folder: true

        - name: "Apply the DBX update"
          include_tasks: test_black_lotus.yml
          when: vm_firmware | lower == "efi"

        - name: "Take snapshot for blacklotus test"
          include_tasks: ../../common/vm_take_snapshot.yml
          vars:
            snapshot_name: "snapshot_for_blacklotus"
            snapshot_description: "Test completed for BlackLotus"
      rescue:
        - name: "Test case failure"
          include_tasks: ../../common/test_rescue.yml
          vars:
            exit_testing_when_fail: true
