# Copyright 2023-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This case is to test Microsoft's Windows updates.
#   Install Windows .msu update package.
#
- name: windows_test
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Test case block"
      block:
        - name: "Test setup"
          include_tasks: ../setup/test_setup.yml
          vars:
            create_current_test_folder: true

        - name: "Set path for copied new boot manager and snapshot name"
          ansible.builtin.set_fact:
            new_bootmgfw_path: "c:\\bootmgfw_2023.efi"
            snapshot_name_for_pca2023: "PCA2023SignedBootmgfw"

        - name: "Revert to original base snapshot"
          include_tasks: ../../common/vm_revert_snapshot.yml
          vars:
            snapshot_name: "{{ snapshot_name_for_pca2023 }}"

        - name: "Copy sigcheck tools to guest OS"
          ansible.builtin.copy:
            src: ./sigcheck
            dest: "C:\\"
          delegate_to: "{{ vm_guest_ip }}"

        - name: "Get digital signature info of {{ new_bootmgfw_path }} by sigcheck"
          include_tasks: ../utils/win_execute_cmd.yml
          vars:
            win_powershell_cmd: >-
              C:\sigcheck\sigcheck.exe -accepteula -i {{ new_bootmgfw_path }}| find "Windows UEFI CA 2023"
            win_execute_cmd_ignore_error: true

        - name: "Check if {{ new_bootmgfw_path }} is sighed with PCA2023"
          ansible.builtin.assert:
            that:
              - win_powershell_cmd_output.stdout_lines is defined
              - win_powershell_cmd_output.stdout_lines | length != 0
            fail_msg: "{{ new_bootmgfw_path }} is not sighed with PCA2023"
            success_msg: "{{ new_bootmgfw_path }} is sighed with PCA2023"
      rescue:
        - name: "Test case failure"
          include_tasks: ../../common/test_rescue.yml
          vars:
            exit_testing_when_fail: true
