# Copyright 2025 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Install WSL distribution

- name: "Set the variables related to WSL distribution installation"
  ansible.builtin.set_fact:
    install_distro_cmd: "wsl --install {{ wsl_distribution_name }} | Out-File -FilePath {{ wsl_file_path_win }}\\wsl_distro_install.txt"
    install_distro_timeout: 600

- name: "Install WSL distribution"
  ansible.windows.win_shell: "{{ install_distro_cmd }}"
  delegate_to: "{{ vm_guest_ip }}"
  register: wsl_distro_install_result
  ignore_errors: true
  async: "{{ install_distro_timeout }}"
  poll: 0

- name: "Check if the WSL distribution is installed"
  include_tasks: check_wsl_distro.yml
  vars:
    wsl_distro_list_timeout: "{{ install_distro_timeout }}"

- name: "Assert if the WSL distribution is not installed"
  ansible.builtin.assert:
    that:
      - wsl_distro_installed
    fail_msg: "Failed to install the WSL distribution: {{ wsl_distribution_name }}."

- name: "Restart the guest OS"
  include_tasks: ../utils/win_shutdown_restart.yml
  vars:
    set_win_power_state: "restart"

- name: "Get the log file for WSL distribution installation"
  include_tasks: wsl_convert_binary_to_txt.yml
  vars:
    source_path: "{{ wsl_file_path_win }}\\wsl_distro_install.txt"
    file_name: "wsl_distro_install.txt"