# Copyright 2023-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
# Run WSL distribution

# Execute command on the distribution
- name: "Set the command executed on WSL distribution "
  ansible.builtin.set_fact:
    distro_command: "cat /etc/os-release"

- name: "Run the WSL distribution"
  include_tasks: ../utils/win_execute_cmd.yml
  vars:
    win_powershell_cmd: "wsl -d {{ wsl_distribution_name }} {{ distro_command}} | Out-File {{ wsl_file_path_win }}\\wsl_run_distro_os_release.txt"
    win_execute_cmd_ignore_error: true

- name: "Process the WSL output message"
  include_tasks: wsl_convert_binary_to_txt.yml
  vars:
    source_path: "{{ wsl_file_path_win }}\\wsl_run_distro_os_release.txt"
    file_name: "wsl_run_distro_os_release.txt"

- name: "Check the execution result of WSL distribution command"
  ansible.builtin.assert:
    that:
      - win_powershell_cmd_output.rc is defined
      - win_powershell_cmd_output.rc == 0
    fail_msg: "The command {{ distro_command }} failed on WSL {{ wsl_distribution_name }} distribution."

- name: "Validate the output of WSL distribution command"
  ansible.builtin.assert:
    that:
      - lookup('ansible.builtin.file', wsl_new_file) is search(wsl_distribution_name)
    fail_msg: "Keyword '{{ wsl_distribution_name }}' is not found in the output of command: {{ distro_command }}."