# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is used for check hotadd and hot remove LSI Logic SAS
# controller and disk. The testing contains 2 parts:
# 1. hotadd new LSI Logic SAS controller and new disk when VM existing
# SCSI controller number < 4.
# 2. hotadd new disk to existing LSILogic controller when there is
# existing LSI Logic SAS controller and the number of disks attached < 16.
#
- name: lsilogicsas_vhba_device_ops
  hosts: localhost
  vars_files:
    - "{{ testing_vars_file | default('../../vars/test.yml') }}"
  vars:
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}"
    scsi_type: "lsilogicsas"
  tasks:
    - include_tasks: vhba_device_hot_add_remove.yml
