# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is used for test Windows VM vCPU hotadd.
# For Windows client: hotadded CPU will not be recognized and used
# after hotadd without OS restart.
# For Windows server: hotadded CPU will be recognized and used after
# hotadd without OS restart.
#
- name: cpu_hot_add_basic
  hosts: localhost
  vars_files:
    - "{{ testing_vars_file | default('../../vars/test.yml') }}"
  tasks:
    - block:
        - include_tasks: ../setup/test_setup.yml
        - include_tasks: ../utils/win_get_guest_type.yml
        
        # Get ESXi host logical processor number as the maximun number of VM cpu hotadd
        - include_tasks: ../../common/esxi_get_property.yml
          vars:
            esxi_host_property_list:
              - summary.hardware.numCpuThreads
        - name: Set fact of the ESXi host logical processor number
          set_fact:
            host_logical_cpu: "{{ esxi_host_property_results.ansible_facts.summary.hardware.numCpuThreads }}"
        
        - name: Set fact of the maximum CPU number for hotadd test
          set_fact:
            max_num_cpus: "{{ [host_logical_cpu|int, vm_cpu_hotadd_max | default(16) |int] | min }}"
        - debug:
            msg: "The maximum hotadded vCPU number set to: {{ max_num_cpus }}"
        
        - name: Initialize the CPU hotadd test result
          set_fact:
            cpu_hotadd_results: []
        - include_tasks: cpu_hot_add_prepare.yml
        - include_tasks: cpu_hot_add_test_server.yml
          when: win_guest_type == "server"
        - include_tasks: cpu_hot_add_test_client.yml
          when: win_guest_type == "client"
        - debug:
            msg: "VM vCPU hotadd result: {{ cpu_hotadd_results | to_yaml }}"
      rescue:
        - include_tasks: ../setup/rescue_cleanup.yml
          vars:
            current_testcase_name: "{{ ansible_play_name }}"
